<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "frab_integration"
 *
 * Auto generated by Extension Builder 2015-05-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Frab Integration',
	'description' => 'This extension integrates the conference tool frab into typo3 (read only)',
	'category' => 'plugin',
	'author' => 'Eike Starkmann',
	'author_email' => 'eikestarkmann@web.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);