<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "frab_integration"
 *
 * Auto generated by Extension Builder 2015-05-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Frab Integration',
    'description' => 'This extension integrates the conference tool frab into typo3 (read only)',
    'category' => 'plugin',
    'author' => 'Eike Starkmann',
    'author_email' => 'eikestarkmann@web.de',
    'state' => 'beta',
    'version' => '4.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.5.0-11.99.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
